# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.define "clojuregoat" do |cg|
  end

  config.vm.network "forwarded_port", guest: 8090, host: 8090, id: "web"
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", auto_correct: false

  config.vm.synced_folder "../", "/var/clojuregoat"

  config.vm.provider :virtualbox do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", 2048]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.limit = "development"
    ansible.playbook = "development_playbook.yml"
    ansible.inventory_path = "development.inventory"
    ansible.sudo = true
  end

end